# Generated by Django 2.0.1 on 2018-01-22 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import isbn_field.fields
import isbn_field.validators
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=255, verbose_name='Apellido')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('imagen', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='autor/', verbose_name='Foto')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=500, verbose_name='Titulo')),
                ('isbn', isbn_field.fields.ISBNField(max_length=28, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('imagen', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='autor/', verbose_name='Foto')),
                ('traductor', models.CharField(blank=True, max_length=500, null=True, verbose_name='Traductor')),
                ('subtitulo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sub Titulo')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Autor')),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Coleccion')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
