# Generated by Django 2.0.1 on 2018-01-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180122_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['apellido', 'nombre', 'created_at'], 'verbose_name_plural': 'Autores'},
        ),
        migrations.AddField(
            model_name='libro',
            name='recomendado',
            field=models.BooleanField(default=False, verbose_name='Recomendado'),
        ),
    ]
