# Generated by Django 2.0.1 on 2018-01-24 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_auto_20180123_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=500, verbose_name='Titulo')),
                ('imagen', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='slider/', verbose_name='Slider')),
                ('activo', models.BooleanField(default=False, verbose_name='Activo')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sliders',
            },
        ),
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='libro/', verbose_name='Foto'),
        ),
    ]
