# Generated by Django 2.0.1 on 2018-01-24 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_auto_20180124_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=500, verbose_name='Título')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('fuente', models.URLField(blank=True, null=True, verbose_name='Fuente')),
                ('firma', models.CharField(blank=True, max_length=500, null=True, verbose_name='Firma')),
                ('medio', models.CharField(blank=True, max_length=500, null=True, verbose_name='Medio')),
                ('subtitulo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sub Título')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Libro')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notas',
            },
        ),
    ]
