# Generated by Django 2.0.1 on 2018-01-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='subtitulo',
            field=models.TextField(blank=True, null=True, verbose_name='Sub Título'),
        ),
    ]
