# Generated by Django 2.0.1 on 2018-01-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180124_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
    ]
