# Generated by Django 2.0.1 on 2018-01-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_nota_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='edicion',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('15,5x23', '155mm*230mm'), ('14x21', '140mm*210mm'), ('13x21', '130mm*210mm'), ('12x21', '120mm*210mm')], null=True, verbose_name='Edición'),
        ),
        migrations.AddField(
            model_name='libro',
            name='formato',
            field=models.CharField(blank=True, choices=[('15,5x23', '155mm*230mm'), ('14x21', '140mm*210mm'), ('13x21', '130mm*210mm'), ('12x21', '120mm*210mm')], max_length=20, null=True, verbose_name='Formato'),
        ),
        migrations.AddField(
            model_name='libro',
            name='paginas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Páginas'),
        ),
        migrations.AddField(
            model_name='libro',
            name='prologo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Prologo de... '),
        ),
    ]
