# Generated by Django 2.0.1 on 2018-01-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180124_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='carrito',
            field=models.URLField(blank=True, null=True, verbose_name='URL Carrito de compras'),
        ),
        migrations.AddField(
            model_name='libro',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploads/pdf/', verbose_name='PDF'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='edicion',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1°'), (2, '2°'), (3, '3°'), (4, '4°'), (5, '5°'), (6, '6°'), (7, '7°'), (8, '8°'), (9, '9°'), (10, '10°'), (11, '11°'), (12, '12°'), (13, '13°'), (14, '14°'), (15, '15°'), (16, '16°'), (17, '17°'), (18, '18°'), (19, '19°'), (20, '20°'), (21, '21°'), (22, '22°'), (23, '23°'), (24, '24°'), (25, '25°'), (26, '26°'), (27, '27°'), (28, '28°'), (29, '29°'), (30, '30°'), (31, '31°'), (32, '32°'), (33, '33°'), (34, '34°'), (35, '35°'), (36, '36°'), (37, '37°'), (38, '38°'), (39, '39°'), (40, '40°'), (41, '41°'), (42, '42°'), (43, '43°'), (44, '44°'), (45, '45°'), (46, '46°'), (47, '47°'), (48, '48°'), (49, '49°'), (50, '50°')], null=True, verbose_name='Edición'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='formato',
            field=models.CharField(blank=True, choices=[('15,5x23', '155mm*230mm'), ('14x21', '140mm*210mm'), ('13x21', '130mm*210mm'), ('12x21', '120mm*210mm'), ('11,8x18', '118mm*180mm')], max_length=20, null=True, verbose_name='Formato'),
        ),
    ]
