# Generated by Django 2.0.1 on 2018-01-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180125_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleccion',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug (uso en la web)'),
        ),
        migrations.AddField(
            model_name='coleccion',
            name='texto',
            field=models.TextField(blank=True, null=True, verbose_name='Texto'),
        ),
    ]
