# Generated by Django 2.0.1 on 2018-01-26 16:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_coleccion_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coleccion',
            options={'ordering': ['orden', 'activa'], 'verbose_name': 'Colección', 'verbose_name_plural': 'Colecciones'},
        ),
        migrations.AlterField(
            model_name='autor',
            name='texto',
            field=tinymce.models.HTMLField(verbose_name='Texto'),
        ),
    ]
