# Generated by Django 2.0.1 on 2018-01-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20180129_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='coleccion',
        ),
        migrations.AddField(
            model_name='libro',
            name='coleccion',
            field=models.ManyToManyField(to='home.Coleccion'),
        ),
    ]
