# Generated by Django 2.0.1 on 2018-01-29 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0017_auto_20180129_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre y Apellido')),
                ('texto', tinymce.models.HTMLField(verbose_name='Texto')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('revisado', models.BooleanField(default=False, verbose_name='Revisado')),
                ('contactado', models.BooleanField(default=False, verbose_name='Contactado')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha Contacto')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
