# Generated by Django 2.0.1 on 2018-01-29 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_contacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={},
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='user',
        ),
    ]
