# Generated by Django 2.0.1 on 2018-01-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20180129_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['-fecha', '-id'], 'verbose_name_plural': 'Libros'},
        ),
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['-fecha', '-created_at'], 'verbose_name_plural': 'Notas'},
        ),
        migrations.AddField(
            model_name='libro',
            name='autores',
            field=models.ManyToManyField(related_name='autores_de_libros', to='home.Autor'),
        ),
    ]
