# Generated by Django 2.0.1 on 2018-02-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_libro_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción (250 chars)'),
        ),
    ]
