# Generated by Django 2.0.1 on 2018-02-07 13:40

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_libro_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleccion',
            name='imagen',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='imagenes/coleccion/', verbose_name='Imagen'),
        ),
    ]
