# Generated by Django 2.0.1 on 2018-02-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_distribucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribucion',
            name='web',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Página web'),
        ),
    ]
