# Generated by Django 2.0.1 on 2018-02-14 21:32

from django.db import migrations, models
import home.models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_coleccion_autores'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=home.models.libro_filename, verbose_name='Foto'),
        ),
    ]
