# Generated by Django 2.0.1 on 2018-02-19 19:30

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_newletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newletter',
            name='revisado',
            field=models.BooleanField(default=False, verbose_name='Revisado'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='subtitulo',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Volanta'),
        ),
    ]
