# Generated by Django 2.0.1 on 2018-02-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20180220_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='autores',
            field=models.ManyToManyField(blank=True, to='home.Autor'),
        ),
    ]
