# Generated by Django 2.0.1 on 2018-02-21 13:49

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('home', '0034_nota_autores'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='libros',
            field=models.ManyToManyField(blank=True, related_name='libros_nota', to='home.Libro'),
        ),
        migrations.AddField(
            model_name='nota',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
