# Generated by Django 2.0.1 on 2018-02-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20180221_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='url1',
            field=models.URLField(blank=True, null=True, verbose_name='URL Nota 1'),
        ),
        migrations.AddField(
            model_name='nota',
            name='url2',
            field=models.URLField(blank=True, null=True, verbose_name='URL Nota 2'),
        ),
        migrations.AddField(
            model_name='nota',
            name='url3',
            field=models.URLField(blank=True, null=True, verbose_name='URL Nota 3'),
        ),
    ]
