# Generated by Django 2.0.1 on 2018-02-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20180221_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='notas',
            field=models.ManyToManyField(blank=True, related_name='_nota_notas_+', to='home.Nota'),
        ),
    ]
