# Generated by Django 2.0.1 on 2018-02-21 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_nota_notas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='url1',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='url2',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='url3',
        ),
    ]
