# Generated by Django 2.0.1 on 2018-02-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_notaurlrelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notarelacion',
            name='nota1',
            field=models.ManyToManyField(related_name='nota_relacionada', to='home.Nota'),
        ),
        migrations.AlterField(
            model_name='notaurlrelacion',
            name='titulo',
            field=models.CharField(max_length=500, verbose_name='Título'),
        ),
    ]
