# Generated by Django 2.0.1 on 2018-02-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20180221_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaurlrelacion',
            name='medio',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Medio y/o Autor'),
        ),
    ]
