# Generated by Django 2.0.1 on 2018-04-25 00:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_notaurlrelacion_medio'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='indice',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Indice'),
        ),
    ]
